services:

  export:
    build:
      context: ./1_dockerExport
    volumes:
      - ./data:/data
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"

  testexport:
    build:
      context: ./2_dockerTestExport
    volumes:
      - ./data:/data
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"
    # depends_on:
    #   export:
    #     condition: service_completed_successfully

  vectorisation:
    build:
      context: ./3_dockerVectorisation
    volumes:
      - ./data:/data
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"
    # depends_on:
    #   testexport:
    #     condition: service_completed_successfully

  testvectorisation:
    build:
      context: ./4_dockerTestVectorisation
    volumes:
      - ./data:/data
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"
    # depends_on:
    #   vectorisation:
    #     condition: service_completed_successfully

  reponse:
    build:
      context: ./5_dockerReponse
    volumes:
      - ./data:/data
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"
    # depends_on:
    #   testvectorisation:
    #     condition: service_completed_successfully

  testragas:
    build:
      context: ./6_dockerRagasTest
    volumes:
      - ./data:/data
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"
    # depends_on:
    #   reponse:
    #     condition: service_completed_successfully

  chatbot:
    build:
      context: ./7_dockerChatBot
    volumes:
      - ./data:/data
    ports:
      - 8501:8501
    env_file: 
      - .env
      - .envFolder
    #command: sh -c "tail -f /dev/null"
    # depends_on:
    #   testragas:
    #     condition: service_completed_successfully

