# ── Source : SQL Server ───────────────────────────────────────────────────────
debezium.source.connector.class=io.debezium.connector.sqlserver.SqlServerConnector
debezium.source.database.hostname=sqlserver
debezium.source.database.port=1433
debezium.source.database.names=StravaDb
debezium.source.database.encrypt=false
debezium.source.topic.prefix=strava
debezium.source.table.include.list=dbo.StravaActivities,dbo.StravaTokens
debezium.source.snapshot.mode=no_data

# Stockage des offsets dans un fichier local (remplace Kafka)
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=5000

# Stockage de l'historique du schéma dans un fichier local (remplace Kafka)
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema-history.dat

# ── Sink : Fichier JSON ───────────────────────────────────────────────────────
# debezium.sink.type=file
# debezium.sink.file.filename=/debezium/data/events.json
debezium.format.value=json
debezium.format.key=json
debezium.sink.type=http
#debezium.sink.http.url=http://webapp:8080/api/debezium/events
debezium.sink.http.url=http://slack:5000/events
